service: alexa-github-stars

custom:
  storageBucket: ${self:service}-bucket

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

functions:
  alexa-github-stars:
    handler: lambda/index.handler
    events:
      - alexaSkill:
          appId: amzn1.ask.skill.5651b8ac-4644-4bbf-a2b0-df4d5bf315b7 #${opt:skillId}
          enabled: false
